# Generated by Django 2.1.7 on 2019-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enrollment_id',
            field=models.IntegerField(unique=True),
        ),
    ]
