# Generated by Django 2.1.7 on 2019-02-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190215_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='enrollment_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
